import Link from 'next/link';

export default function LandingPage() {
  const features = [
    {
      title: 'AI SOP Generator',
      description:
        'Generate professional Statements of Purpose tailored to your academic background and goals.',
      icon: '📝',
    },
    {
      title: 'Profile Analyzer',
      description:
        'Analyze your academic profile and receive AI-powered admission insights.',
      icon: '📊',
    },
    {
      title: 'University Finder',
      description:
        'Discover universities based on your GPA, budget, country preference, and interests.',
      icon: '🎓',
    },
    {
      title: 'Document Checker',
      description:
        'Verify your application documents before submission and reduce mistakes.',
      icon: '📂',
    },
    {
      title: 'AI Assistant',
      description:
        'Ask questions about admissions, scholarships, visas, and applications anytime.',
      icon: '🤖',
    },
    {
      title: 'Centralized Dashboard',
      description:
        'Manage all your admission tasks, SOPs, universities, and progress in one place.',
      icon: '🚀',
    },
  ]

  const steps = [
    {
      title: 'Create Your Profile',
      description:
        'Add your academic details, goals, and preferred study destination.',
    },
    {
      title: 'Use AI Tools',
      description:
        'Generate SOPs, analyze your profile, and discover universities instantly.',
    },
    {
      title: 'Apply Smarter',
      description:
        'Prepare stronger applications with AI-powered guidance and insights.',
    },
  ]

  const faqs = [
    {
      q: 'Is AI Admission free to use?',
      a: 'Yes, we offer a free plan with essential features for students getting started.',
    },
    {
      q: 'Which countries are supported?',
      a: 'Our platform supports university admissions for multiple countries including the USA, UK, Canada, Australia, and Europe.',
    },
    {
      q: 'Can I edit generated SOPs?',
      a: 'Absolutely. Every SOP generated by AI can be customized and edited by the user.',
    },
    {
      q: 'How accurate is the profile analysis?',
      a: 'Our AI provides guidance based on your profile and university data, but final decisions depend on university admission committees.',
    },
  ]

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Navbar */}
      <nav className="sticky top-0 z-50 border-b border-white/10 bg-black/80 backdrop-blur-lg">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2">
            <div className="h-10 w-10 rounded-xl bg-indigo-600 flex items-center justify-center font-bold text-lg">
              AI
            </div>
            <div>
              <h1 className="text-lg font-bold">AI Admission</h1>
              <p className="text-xs text-gray-400">by Ariesian Tech</p>
            </div>
          </div>

          <div className="hidden md:flex items-center gap-8 text-sm text-gray-300">
            <a href="#features" className="hover:text-white transition">Features</a>
            <a href="#how" className="hover:text-white transition">How It Works</a>
            <a href="#pricing" className="hover:text-white transition">Pricing</a>
            <a href="#faq" className="hover:text-white transition">FAQ</a>
          </div>

          <div className="flex items-center gap-3">
            <Link href="/login" className="rounded-xl border border-white/10 px-4 py-2 text-sm hover:bg-white/10 transition">
              Login
            </Link>
            <Link href="/signup" className="rounded-xl bg-indigo-600 px-5 py-2 text-sm font-medium hover:bg-indigo-500 transition">
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(99,102,241,0.25),transparent_40%)]"></div>

        <div className="relative mx-auto grid max-w-7xl grid-cols-1 items-center gap-16 px-6 py-24 lg:grid-cols-2">
          <div>
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-indigo-500/20 bg-indigo-500/10 px-4 py-2 text-sm text-indigo-300">
              🚀 AI-Powered University Admission Platform
            </div>

            <h1 className="text-5xl font-bold leading-tight md:text-6xl">
              Get Admitted <span className="text-indigo-500">Smarter</span> with AI
            </h1>

            <p className="mt-6 max-w-xl text-lg leading-8 text-gray-400">
              Generate SOPs, analyze your profile, discover universities, and prepare your applications — all in one intelligent platform.
            </p>

            <div className="mt-8 flex flex-wrap gap-4">
              <Link href="/signup" className="rounded-2xl bg-indigo-600 px-7 py-4 font-medium hover:bg-indigo-500 transition">
                Start Free
              </Link>

              <a
                href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                target="_blank"
                rel="noopener noreferrer"
                className="rounded-2xl border border-white/10 px-7 py-4 font-medium hover:bg-white/10 transition"
              >
                Watch Demo
              </a>
            </div>

            <div className="mt-10 flex flex-wrap gap-4 text-sm text-gray-400">
              <div className="rounded-full border border-white/10 px-4 py-2">
                🤖 AI Powered
              </div>
              <div className="rounded-full border border-white/10 px-4 py-2">
                🎓 University Matching
              </div>
              <div className="rounded-full border border-white/10 px-4 py-2">
                🔒 Secure Platform
              </div>
            </div>
          </div>

          {/* Dashboard Preview */}
          <div className="relative">
            <div className="absolute -inset-4 rounded-4xl bg-indigo-500/20 blur-3xl"></div>

            <div className="relative rounded-4xl border border-white/10 bg-white/5 p-5 backdrop-blur-xl shadow-2xl">
              <div className="mb-4 flex items-center gap-2">
                <div className="h-3 w-3 rounded-full bg-red-500"></div>
                <div className="h-3 w-3 rounded-full bg-yellow-500"></div>
                <div className="h-3 w-3 rounded-full bg-green-500"></div>
              </div>

              <div className="grid gap-4 md:grid-cols-2">
                <div className="rounded-2xl bg-black/40 p-5 border border-white/10">
                  <h3 className="text-lg font-semibold">Admission Score</h3>
                  <p className="mt-2 text-4xl font-bold text-indigo-400">87%</p>
                  <p className="mt-2 text-sm text-gray-400">Strong profile for Canadian universities.</p>
                </div>

                <div className="rounded-2xl bg-black/40 p-5 border border-white/10">
                  <h3 className="text-lg font-semibold">SOP Generated</h3>
                  <p className="mt-2 text-4xl font-bold text-indigo-400">12</p>
                  <p className="mt-2 text-sm text-gray-400">AI-generated SOP drafts available.</p>
                </div>

                <div className="rounded-2xl bg-black/40 p-5 border border-white/10 md:col-span-2">
                  <h3 className="mb-4 text-lg font-semibold">Recommended Universities</h3>

                  <div className="space-y-3">
                    <div className="flex items-center justify-between rounded-xl bg-white/5 px-4 py-3">
                      <div>
                        <p className="font-medium">University of Toronto</p>
                        <p className="text-sm text-gray-400">Canada</p>
                      </div>
                      <span className="rounded-full bg-green-500/10 px-3 py-1 text-sm text-green-400">
                        High Match
                      </span>
                    </div>

                    <div className="flex items-center justify-between rounded-xl bg-white/5 px-4 py-3">
                      <div>
                        <p className="font-medium">University of Melbourne</p>
                        <p className="text-sm text-gray-400">Australia</p>
                      </div>
                      <span className="rounded-full bg-yellow-500/10 px-3 py-1 text-sm text-yellow-400">
                        Medium Match
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Problem & Solution */}
      <section className="border-t border-white/10 bg-white/2">
        <div className="mx-auto max-w-7xl px-6 py-24">
          <div className="grid gap-10 lg:grid-cols-2">
            <div className="rounded-3xl border border-red-500/10 bg-red-500/5 p-10">
              <h2 className="text-3xl font-bold">The Problem</h2>

              <ul className="mt-6 space-y-4 text-gray-300">
                <li>❌ Students struggle with writing SOPs</li>
                <li>❌ Finding suitable universities is confusing</li>
                <li>❌ Admission chances are unclear</li>
                <li>❌ Application documents often contain mistakes</li>
              </ul>
            </div>

            <div className="rounded-3xl border border-indigo-500/10 bg-indigo-500/5 p-10">
              <h2 className="text-3xl font-bold">Our Solution</h2>

              <p className="mt-6 text-lg leading-8 text-gray-300">
                AI Admission simplifies the entire admission journey using artificial intelligence — from SOP generation to university matching and profile analysis.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features">
        <div className="mx-auto max-w-7xl px-6 py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">
              Features
            </p>
            <h2 className="mt-4 text-4xl font-bold">
              Everything You Need for University Admissions
            </h2>
          </div>

          <div className="mt-16 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="rounded-3xl border border-white/10 bg-white/3 p-8 hover:border-indigo-500/30 hover:bg-indigo-500/5 transition"
              >
                <div className="text-4xl">{feature.icon}</div>
                <h3 className="mt-5 text-2xl font-semibold">{feature.title}</h3>
                <p className="mt-4 leading-7 text-gray-400">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how" className="border-y border-white/10 bg-white/2">
        <div className="mx-auto max-w-7xl px-6 py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">
              How It Works
            </p>
            <h2 className="mt-4 text-4xl font-bold">
              Simple, Fast, Intelligent
            </h2>
          </div>

          <div className="mt-16 grid gap-8 md:grid-cols-3">
            {steps.map((step, index) => (
              <div
                key={step.title}
                className="rounded-3xl border border-white/10 bg-black/30 p-8"
              >
                <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-600 text-xl font-bold">
                  {index + 1}
                </div>

                <h3 className="mt-6 text-2xl font-semibold">{step.title}</h3>

                <p className="mt-4 leading-7 text-gray-400">
                  {step.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section>
        <div className="mx-auto max-w-7xl px-6 py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">
              Testimonials
            </p>
            <h2 className="mt-4 text-4xl font-bold">
              Students Love Using AI Admission
            </h2>
          </div>

          <div className="mt-16 grid gap-6 md:grid-cols-3">
            {[
              'The SOP generator saved me hours of work and helped me structure my application professionally.',
              'The university recommendations were surprisingly accurate for my profile.',
              'This platform made the entire admission process much easier and less stressful.',
            ].map((review, i) => (
              <div
                key={i}
                className="rounded-3xl border border-white/10 bg-white/3 p-8"
              >
                <div className="mb-4 text-2xl">⭐️⭐️⭐️⭐️⭐️</div>
                <p className="leading-8 text-gray-300">“{review}”</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="border-y border-white/10 bg-white/2">
        <div className="mx-auto max-w-7xl px-6 py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">
              Pricing
            </p>
            <h2 className="mt-4 text-4xl font-bold">
              Start Free, Upgrade Anytime
            </h2>
          </div>

          <div className="mt-16 grid gap-8 lg:grid-cols-2">
            <div className="rounded-3xl border border-white/10 bg-black/40 p-10">
              <h3 className="text-3xl font-bold">Free</h3>
              <p className="mt-4 text-5xl font-bold">$0</p>

              <ul className="mt-8 space-y-4 text-gray-300">
                <li>✔ Limited SOP Generation</li>
                <li>✔ Basic Profile Analysis</li>
                <li>✔ University Search</li>
                <li>✔ AI Chat Access</li>
              </ul>

              <Link href="/signup" className="mt-10 block w-full rounded-2xl border border-white/10 py-4 text-center hover:bg-white/10 transition">
                Get Started
              </Link>
            </div>

            <div className="rounded-3xl border border-indigo-500 bg-indigo-500/10 p-10 shadow-2xl shadow-indigo-500/20">
              <div className="mb-4 inline-flex rounded-full bg-indigo-500 px-4 py-2 text-sm font-medium">
                Most Popular
              </div>

              <h3 className="text-3xl font-bold">Pro</h3>
              <p className="mt-4 text-5xl font-bold">PKR 800</p>

              <ul className="mt-8 space-y-4 text-gray-200">
                <li>✔ Unlimited SOP Generation</li>
                <li>✔ Advanced AI Analysis</li>
                <li>✔ Priority University Matching</li>
                <li>✔ Premium AI Assistance</li>
                <li>✔ Future Scholarship Finder</li>
              </ul>

              <Link href="/checkout" className="mt-10 block w-full rounded-2xl bg-indigo-600 py-4 text-center font-medium hover:bg-indigo-500 transition">
                Upgrade to Pro
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq">
        <div className="mx-auto max-w-5xl px-6 py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">
              FAQ
            </p>
            <h2 className="mt-4 text-4xl font-bold">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="mt-16 space-y-6">
            {faqs.map((faq) => (
              <div
                key={faq.q}
                className="rounded-3xl border border-white/10 bg-white/3 p-8"
              >
                <h3 className="text-xl font-semibold">{faq.q}</h3>
                <p className="mt-4 leading-7 text-gray-400">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="relative overflow-hidden border-t border-white/10">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(99,102,241,0.25),transparent_50%)]"></div>

        <div className="relative mx-auto max-w-5xl px-6 py-28 text-center">
          <h2 className="text-5xl font-bold leading-tight">
            Start Your Admission Journey with AI
          </h2>

          <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-gray-400">
            Join students using AI Admission to prepare stronger university applications faster and smarter.
          </p>

          <Link href="/signup" className="mt-10 inline-flex rounded-2xl bg-indigo-600 px-10 py-5 text-lg font-medium hover:bg-indigo-500 transition">
            Get Started Free
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/10 bg-black">
        <div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 px-6 py-10 text-center md:flex-row md:text-left">
          <div>
            <h3 className="text-xl font-bold">AI Admission</h3>
            <p className="mt-2 text-sm text-gray-500">
              Built by Ariesian Tech
            </p>
          </div>

          <div className="flex flex-wrap justify-center gap-6 text-sm text-gray-400">
            <a href="#" className="hover:text-white transition">
              Privacy Policy
            </a>
            <a href="#" className="hover:text-white transition">
              Terms & Conditions
            </a>
            <a href="#" className="hover:text-white transition">
              Contact
            </a>
          </div>
        </div>
      </footer>
    </div>
  )
}
