'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { onAuthStateChanged } from 'firebase/auth';
import { auth } from '@/lib/firebase';

export default function LandingPage() {
  const router = useRouter();
  const [menuOpen, setMenuOpen] = useState(false);
  const [checking, setChecking] = useState(true);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) router.replace('/dashboard');
      else setChecking(false);
    });

    return () => unsubscribe();
  }, [router]);

  if (checking) return null;

  const features = [
    { title: 'AI SOP Generator', description: 'Generate professional Statements of Purpose tailored to your academic background and goals.', icon: '📝' },
    { title: 'Profile Analyzer', description: 'Analyze your academic profile and receive AI-powered admission insights and scoring.', icon: '📊' },
    { title: 'University Finder', description: 'Discover universities based on your GPA, budget, country preference, and interests.', icon: '🎓' },
    { title: 'Document Checker', description: 'Verify your application documents before submission and reduce costly mistakes.', icon: '📂' },
    { title: 'AI Assistant', description: 'Ask questions about admissions, scholarships, visas, and applications anytime.', icon: '🤖' },
    { title: 'Centralized Dashboard', description: 'Manage all your admission tasks, SOPs, universities, and progress in one place.', icon: '🚀' },
  ];

  const steps = [
    { title: 'Create Your Profile', description: 'Add your academic details, goals, and preferred study destination.' },
    { title: 'Use AI Tools', description: 'Generate SOPs, analyze your profile, and discover universities instantly.' },
    { title: 'Apply Smarter', description: 'Prepare stronger applications with AI-powered guidance and insights.' },
  ];

  const faqs = [
    { q: 'Is UniQuest AI free to use?', a: 'Yes, we offer a free plan with essential features including limited SOP generation, profile analysis, university search, and AI chat.' },
    { q: 'Which countries are supported?', a: 'Our platform supports university admissions for multiple countries including the USA, UK, Canada, Australia, Germany, and Europe.' },
    { q: 'Can I edit generated SOPs?', a: 'Absolutely. Every SOP generated by AI can be copied, customized, and edited by the user before submission.' },
    { q: 'How accurate is the profile analysis?', a: 'Our AI provides data-driven guidance based on your profile and university requirements, but final admission decisions depend on university committees.' },
    { q: 'How do I upgrade to Pro?', a: 'Click "Upgrade to Pro" from your dashboard or the pricing section. We accept all major cards, Apple Pay, Google Pay, and PayPal.' },
  ];

  return (
    <div className="min-h-screen bg-black text-white">

      {/* Navbar */}
      <nav className="sticky top-0 z-50 border-b border-white/10 bg-black/80 backdrop-blur-lg">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6">

          {/* Logo */}
          <div className="flex items-center gap-2.5">
            <Image
              src="/logo.png"
              alt="UniQuest AI"
              width={36}
              height={36}
              className="rounded-xl shrink-0"
            />
            <div>
              <h1 className="text-base font-bold leading-tight">UniQuest AI</h1>
              <p className="text-[10px] text-gray-400">by Ariesian Tech</p>
            </div>
          </div>

          {/* Desktop nav */}
          <div className="hidden md:flex items-center gap-8 text-sm text-gray-300">
            <a href="#features" className="hover:text-white transition">Features</a>
            <a href="#how" className="hover:text-white transition">How It Works</a>
            <a href="#pricing" className="hover:text-white transition">Pricing</a>
            <a href="#faq" className="hover:text-white transition">FAQ</a>
          </div>

          <div className="hidden md:flex items-center gap-3">
            <Link href="/login" className="rounded-xl border border-white/10 px-4 py-2 text-sm hover:bg-white/10 transition">
              Login
            </Link>
            <Link href="/signup" className="rounded-xl bg-indigo-600 px-5 py-2 text-sm font-medium hover:bg-indigo-500 transition">
              Get Started
            </Link>
          </div>

          {/* Mobile hamburger */}
          <button
            className="md:hidden p-2 rounded-lg border border-white/10 hover:bg-white/10 transition"
            onClick={() => setMenuOpen(!menuOpen)}
          >
            {menuOpen ? (
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            ) : (
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            )}
          </button>
        </div>

        {/* Mobile menu */}
        {menuOpen && (
          <div className="md:hidden border-t border-white/10 bg-black/95 px-4 py-4 space-y-3">
            {['#features', '#how', '#pricing', '#faq'].map((href) => (
              <a
                key={href}
                href={href}
                onClick={() => setMenuOpen(false)}
                className="block text-sm text-gray-300 hover:text-white py-2 transition capitalize"
              >
                {href.replace('#', '').replace('-', ' ')}
              </a>
            ))}
            <div className="pt-3 flex flex-col gap-2 border-t border-white/10">
              <Link href="/login" className="block text-center rounded-xl border border-white/10 px-4 py-2.5 text-sm hover:bg-white/10 transition">
                Login
              </Link>
              <Link href="/signup" className="block text-center rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-medium hover:bg-indigo-500 transition">
                Get Started
              </Link>
            </div>
          </div>
        )}
      </nav>

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(99,102,241,0.25),transparent_40%)]" />
        <div className="relative mx-auto grid max-w-7xl grid-cols-1 items-center gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-2">
          <div>
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-indigo-500/20 bg-indigo-500/10 px-4 py-2 text-sm text-indigo-300">
              🚀 AI-Powered University Admission Platform
            </div>
            <h1 className="text-4xl font-bold leading-tight sm:text-5xl md:text-6xl">
              Get Admitted <span className="text-indigo-500">Smarter</span> with AI
            </h1>
            <p className="mt-6 max-w-xl text-base leading-8 text-gray-400 sm:text-lg">
              Generate SOPs, analyze your profile, discover universities, and prepare your applications — all in one intelligent platform.
            </p>
            <div className="mt-8 flex flex-wrap gap-4">
              <Link href="/signup" className="rounded-2xl bg-indigo-600 px-7 py-4 font-medium hover:bg-indigo-500 transition">
                Start Free
              </Link>
              <a href="#features" className="rounded-2xl border border-white/10 px-7 py-4 font-medium hover:bg-white/10 transition">
                See Features ↓
              </a>
            </div>
            <div className="mt-10 flex flex-wrap gap-3 text-sm text-gray-400">
              <div className="rounded-full border border-white/10 px-4 py-2">🤖 AI Powered</div>
              <div className="rounded-full border border-white/10 px-4 py-2">🎓 University Matching</div>
              <div className="rounded-full border border-white/10 px-4 py-2">🔒 Secure Platform</div>
            </div>
          </div>

          {/* Dashboard Preview */}
          <div className="relative">
            <div className="absolute -inset-4 rounded-3xl bg-indigo-500/20 blur-3xl" />
            <div className="relative rounded-3xl border border-white/10 bg-white/5 p-4 sm:p-5 backdrop-blur-xl shadow-2xl">
              <div className="mb-4 flex items-center gap-2">
                <div className="h-3 w-3 rounded-full bg-red-500" />
                <div className="h-3 w-3 rounded-full bg-yellow-500" />
                <div className="h-3 w-3 rounded-full bg-green-500" />
              </div>
              <div className="grid gap-4 grid-cols-2">
                <div className="rounded-2xl bg-black/40 p-4 border border-white/10">
                  <h3 className="text-sm font-semibold">Admission Score</h3>
                  <p className="mt-2 text-3xl font-bold text-indigo-400">87%</p>
                  <p className="mt-1 text-xs text-gray-400">Strong profile for Canadian universities.</p>
                </div>
                <div className="rounded-2xl bg-black/40 p-4 border border-white/10">
                  <h3 className="text-sm font-semibold">SOPs Generated</h3>
                  <p className="mt-2 text-3xl font-bold text-indigo-400">12</p>
                  <p className="mt-1 text-xs text-gray-400">AI-generated SOP drafts.</p>
                </div>
                <div className="rounded-2xl bg-black/40 p-4 border border-white/10 col-span-2">
                  <h3 className="mb-3 text-sm font-semibold">Recommended Universities</h3>
                  <div className="space-y-2">
                    {[
                      { name: 'University of Toronto', country: 'Canada', match: 'High Match', color: 'text-green-400 bg-green-500/10' },
                      { name: 'University of Melbourne', country: 'Australia', match: 'Medium Match', color: 'text-yellow-400 bg-yellow-500/10' },
                    ].map((u) => (
                      <div key={u.name} className="flex items-center justify-between rounded-xl bg-white/5 px-3 py-2.5">
                        <div>
                          <p className="text-sm font-medium">{u.name}</p>
                          <p className="text-xs text-gray-400">{u.country}</p>
                        </div>
                        <span className={`rounded-full px-2.5 py-1 text-xs ${u.color}`}>{u.match}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Problem & Solution */}
      <section className="border-t border-white/10">
        <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24">
          <div className="grid gap-6 sm:grid-cols-2">
            <div className="rounded-3xl border border-red-500/10 bg-red-500/5 p-8 sm:p-10">
              <h2 className="text-2xl font-bold sm:text-3xl">The Problem</h2>
              <ul className="mt-6 space-y-4 text-gray-300 text-sm sm:text-base">
                <li>❌ Students struggle with writing SOPs</li>
                <li>❌ Finding suitable universities is confusing</li>
                <li>❌ Admission chances are unclear</li>
                <li>❌ Application documents often contain mistakes</li>
              </ul>
            </div>
            <div className="rounded-3xl border border-indigo-500/10 bg-indigo-500/5 p-8 sm:p-10">
              <h2 className="text-2xl font-bold sm:text-3xl">Our Solution</h2>
              <p className="mt-6 text-base leading-8 text-gray-300">
                UniQuest AI simplifies the entire admission journey using artificial intelligence — from SOP generation to university matching and profile analysis.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="border-t border-white/10">
        <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">Features</p>
            <h2 className="mt-4 text-3xl font-bold sm:text-4xl">Everything You Need for University Admissions</h2>
          </div>
          <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((f) => (
              <div key={f.title} className="rounded-3xl border border-white/10 bg-white/3 p-6 sm:p-8 hover:border-indigo-500/30 hover:bg-indigo-500/5 transition">
                <div className="text-3xl">{f.icon}</div>
                <h3 className="mt-4 text-lg font-semibold sm:text-xl">{f.title}</h3>
                <p className="mt-3 text-sm leading-7 text-gray-400">{f.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how" className="border-y border-white/10 bg-white/2">
        <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">How It Works</p>
            <h2 className="mt-4 text-3xl font-bold sm:text-4xl">Simple, Fast, Intelligent</h2>
          </div>
          <div className="mt-12 grid gap-6 sm:grid-cols-3">
            {steps.map((step, i) => (
              <div key={step.title} className="rounded-3xl border border-white/10 bg-black/30 p-6 sm:p-8">
                <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-600 text-lg font-bold">{i + 1}</div>
                <h3 className="mt-5 text-lg font-semibold sm:text-xl">{step.title}</h3>
                <p className="mt-3 text-sm leading-7 text-gray-400">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="border-b border-white/10">
        <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">Testimonials</p>
            <h2 className="mt-4 text-3xl font-bold sm:text-4xl">Students Love Using UniQuest AI</h2>
          </div>
          <div className="mt-12 grid gap-5 sm:grid-cols-3">
            {[
              { review: 'The SOP generator saved me hours of work and helped me structure my application professionally.', name: 'Ahmed R.', country: 'Pakistan' },
              { review: 'The university recommendations were surprisingly accurate for my profile and budget.', name: 'Sarah M.', country: 'Egypt' },
              { review: 'This platform made the entire admission process much easier and less stressful.', name: 'Ali K.', country: 'Bangladesh' },
            ].map((t, i) => (
              <div key={i} className="rounded-3xl border border-white/10 bg-white/3 p-6 sm:p-8">
                <div className="mb-3 text-xl">⭐️⭐️⭐️⭐️⭐️</div>
                <p className="text-sm leading-7 text-gray-300">"{t.review}"</p>
                <p className="mt-4 text-xs text-gray-500">— {t.name}, {t.country}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="border-b border-white/10 bg-white/2">
        <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">Pricing</p>
            <h2 className="mt-4 text-3xl font-bold sm:text-4xl">Start Free, Upgrade Anytime</h2>
          </div>
          <div className="mt-12 grid gap-6 sm:grid-cols-2 max-w-4xl mx-auto">
            <div className="rounded-3xl border border-white/10 bg-black/40 p-8 sm:p-10">
              <h3 className="text-2xl font-bold">Free</h3>
              <p className="mt-3 text-4xl font-bold">PKR 0 <span className="text-lg font-normal text-gray-400">/month</span></p>
              <ul className="mt-8 space-y-3 text-sm text-gray-300">
                <li>✔ 3 SOP Generations</li>
                <li>✔ 2 Profile Analyses</li>
                <li>✔ 10 AI Chat Messages</li>
                <li>✔ 3 Scholarship Searches</li>
                <li>✔ University Search</li>
              </ul>
              <Link href="/signup" className="mt-8 block w-full rounded-2xl border border-white/10 py-3.5 text-center text-sm hover:bg-white/10 transition">
                Get Started Free
              </Link>
            </div>
            <div className="rounded-3xl border border-indigo-500 bg-indigo-500/10 p-8 sm:p-10 shadow-2xl shadow-indigo-500/20">
              <div className="mb-4 inline-flex rounded-full bg-indigo-500 px-4 py-1.5 text-xs font-medium">Most Popular</div>
              <h3 className="text-2xl font-bold">Pro</h3>
              <p className="mt-3 text-4xl font-bold">PKR 800 <span className="text-lg font-normal text-gray-300">/month</span></p>
              <ul className="mt-8 space-y-3 text-sm text-gray-200">
                <li>✔ Unlimited SOP Generations</li>
                <li>✔ Unlimited Profile Analyses</li>
                <li>✔ Unlimited AI Chat</li>
                <li>✔ Unlimited Scholarship Searches</li>
                <li>✔ Priority University Matching</li>
                <li>✔ 7-day free trial</li>
              </ul>
              <Link href="/checkout" className="mt-8 block w-full rounded-2xl bg-indigo-600 py-3.5 text-center text-sm font-medium hover:bg-indigo-500 transition">
                Upgrade to Pro
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq">
        <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 sm:py-24">
          <div className="text-center">
            <p className="text-sm uppercase tracking-[0.3em] text-indigo-400">FAQ</p>
            <h2 className="mt-4 text-3xl font-bold sm:text-4xl">Frequently Asked Questions</h2>
          </div>
          <div className="mt-12 space-y-5">
            {faqs.map((faq) => (
              <div key={faq.q} className="rounded-3xl border border-white/10 bg-white/3 p-6 sm:p-8">
                <h3 className="text-base font-semibold sm:text-lg">{faq.q}</h3>
                <p className="mt-3 text-sm leading-7 text-gray-400">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="relative overflow-hidden border-t border-white/10">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(99,102,241,0.25),transparent_50%)]" />
        <div className="relative mx-auto max-w-4xl px-4 py-20 text-center sm:px-6 sm:py-28">
          <h2 className="text-3xl font-bold leading-tight sm:text-5xl">Start Your Admission Journey with AI</h2>
          <p className="mx-auto mt-6 max-w-2xl text-base leading-8 text-gray-400">
            Join students using UniQuest AI to prepare stronger university applications faster and smarter.
          </p>
          <Link href="/signup" className="mt-8 inline-flex rounded-2xl bg-indigo-600 px-8 py-4 text-base font-medium hover:bg-indigo-500 transition sm:px-10 sm:py-5 sm:text-lg">
            Get Started Free
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/10 bg-black">
        <div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 px-4 py-10 text-center sm:px-6 md:flex-row md:text-left">
          <div className="flex items-center gap-2.5">
            <Image
              src="/logo.png"
              alt="UniQuest AI"
              width={32}
              height={32}
              className="rounded-lg shrink-0"
            />
            <div>
              <h3 className="text-base font-bold">UniQuest AI</h3>
              <p className="text-xs text-gray-500">Built by Ariesian Tech</p>
            </div>
          </div>
          <div className="flex flex-wrap justify-center gap-6 text-sm text-gray-400">
            <Link href="/privacy" className="hover:text-white transition">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-white transition">Terms & Conditions</Link>
            <Link href="/contact" className="hover:text-white transition">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
